---
  sensor_config:
    description: "ActiveMQ Sensor settings"
    type: "object"
    required: true
    additionalProperties: true
    properties:
      hosts:
        description: "ActiveMQ hosts to connect to"
        type: "array"
        items:
          type: "string"
          required: true
      username:
        description: "Username for ActiveMQ"
        type: "string"
      password:
        description: "Password for ActiveMQ"
        type: "string"
        secret: true
      activemq_topic_sensor:
        description: "Topic settings"
        type: "object"
        required: true
        additionalProperties: true
        properties:
          topics:
            description: "List of topics to monitor"
            type: "array"
            items:
              type: "string"
              required: true
          deserialization_method:
            description: "Method used to de-serialize body. Default is to leave body as-is"
            type: "string"
            enum:
              - "json"
              - "pickle"
            required: false
